// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dlyvaxxfheefketazsag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRseXZheHhmaGVlZmtldGF6c2FnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNDQwODUsImV4cCI6MjA2MDYyMDA4NX0.wYivi2j8jRmK5-m9I6JUw-Lp8KpRCtunSBnj4RCgGTA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);